package com.onbank.api.model;

public enum enumTypeofOperation{
    PRZELEW_WLASNY,
    PRZELEW_WYCHODZACY,
    PRZELEW_PRZYCHODZACY,
    PRZELEW_PODATKOWY,
    PRZELEW_ZUS,
    PRZELEW_MAKLERSKI,
    OPERACJA_KREDYTOWA,
    REGULARNE_OSZCZEDZANIE,
    OPERACJA_WALUTOWA,
    WYPLATY_GOTOWKOWE,
    WPLATY_GOTOWKOWE,
    OPLATY,
    KAPITALIZACJA_ODSETEK,
    POZOSTALE_OPERACJE
}