package com.onbank.api.model;

public enum OperationType {
    OWN_TRANSFER,
    OVERCOMING_TRANSFER,
    INCOMING_TRANSFER,
    TAX_TRANSFER,
    ZUS_TRANSFER,
    BROKERAGE_TRANSFER,
    CREDIT_OPERATION,
    CURRENCY_OPERATION,
    CASH_PAYMENTS,
    CHARGES,
    CAPITALIZATION,
    OTHERS
}